 
FROM mcr.microsoft.com/windows/servercore:ltsc2022

# Install vcpkg and dependencies
# (This will be expanded later)

WORKDIR /app
COPY . .

# Build and run commands will go here
CMD ["SnakeAI-MLOps.exe"]